spring:
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
